kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wikijs-pv-claim
  namespace: wikijs
spec:
  storageClassName: longhorn-test 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
