apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wikijs
type: Opaque
data:
  ROOT: rootName
  ROOT_PASSWORD: rootPassword
  DATABASE: dbName
  USER: userName
  PASSWORD: userPassword
