authentik:
    log_level: debug
    secret_key: "<your secret key>"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        host: "database-pooler.authentik-ha.svc.cluster.local"
        name: "authentik"
        user: "user"
        password: "<plain text password>"
        port: 5432
    redis:
        host: "dragonfly-cluster.authentik-ha.svc.cluster.local"
        port: 6379
        password: "<plain text password>"  # Set this if Redis requires authentication

postgresql:
    enabled: false
redis:
    enabled: false

global:
  env:
  - name: AUTHENTIK_POSTGRESQL__USE_PGPOOL
    value: "true"

server:
  # -- authentik server name
  name: server

  # -- The number of server pods to run
  replicas: 3

## authentik worker   
worker:
  # -- authentik worker name
  name: worker

  # -- The number of worker pods to run
  replicas: 3
