authentik:
    log_level: debug
    secret_key: "<your secret key>"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        host: "database-cluster-rw.authentik-ha.svc.cluster.local"
        name: "authentik"
        user: "user"
        password: "<plain text password>"
        port: 5432
    redis:
        host: "redis-redis-cluster.authentik-ha.svc.cluster.local"
        port: 6379
        password: "<plain text password>"  # Set this if Redis requires authentication
      #db: 0

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        enabled: true
        hosts:
            - auth2.silverycat.de
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
            - secretName: auth2-silverycat-de-tls
              hosts:
                - auth2.silverycat.de
postgresql:
    enabled: false
redis:
    enabled: false

global:
  env:
  - name: AUTHENTIK_POSTGRESQL__USE_PGPOOL
    value: "true"

server:
  # -- authentik server name
  name: server

  # -- The number of server pods to run
  replicas: 3

## authentik worker   
worker:
  # -- authentik worker name
  name: worker

  # -- The number of worker pods to run
  replicas: 3
