apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-auth
  namespace: authentik-ha
type: Opaque
data:
  password: <inserrt a base64 password>
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly
  namespace: authentik-ha
spec:
  replicas: 3
  authentication:
    passwordFromSecret:
      name: dragonfly-auth
      key: password
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
