#This is a preconfigured values parameters for the installation of nextcloud with helm

# Number of replicas to be deployed
replicaCount: 1
ingress:
  enabled: true
  className: nginx
  tls:
     - secretName: next-neptune87-cloud-tls
       hosts:
         - next.neptune87.cloud
nextcloud:
  host: next.neptune87.cloud
  username: admin
  password: changeme

  configs: {}

nginx:
  enabled: false
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  containerPort: 80

persistence:
  enabled: true
  annotations: {}
  storageClass: "local-path"
  existingClaim: nextcloud-server-pvc

phpClientHttpsFix:
  enabled: true
  protocol: https

#This should be added if using distributed storage like longhorn, to avoid timeout error non the inizialization of nextcloud pod
startupProbe:
  enabled: true
  initialDelaySeconds: 240
  failureThreshold: 50
