replicaCount: 3

ingress:
   enabled: true
   className: traefik
   annotations:
       cert-manager.io/cluster-issuer: letsencrypt-production
       acme.cert-manager.io/http01-edit-in-place: "true"
       traefik.ingress.kubernetes.io/redirect-entry-point: https
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
       traefik.ingress.kubernetes.io/router.tls: "true"
       traefik.ingress.kubernetes.io/service.sticky: "true"
       traefik.ingress.kubernetes.io/service.sticky.cookie: "WOPI-SESSION"
       traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
   hosts:
      - host: "collabora.silverycat.de"
        paths:
        - path: /
          pathType: ImplementationSpecific
   tls:
      - secretName: collabora-silverycat-de-tls
        hosts:
          - collabora.silverycat.de

image:
   tag: "latest"

autoscaling:
   enabled: false

collabora:
   aliasgroups:
     - host: "https://store.silverycat.de:443"
   extra_params: --o:ssl.enable=false --o:ssl.termination=true
   # for production enviroment we recommend appending `extra_params` with `--o:num_prespawn_children=4`. It defines number of child processes to keep started in advance and waiting for new clients

#resources:
#   limits:
#      cpu: "1800m"
#      memory: "2000Mi"
#   requests:
#      cpu: "1800m"
#      memory: "2000Mi"
