manager:
  # If false, manager will not be installed
  enabled: true
  image:
    repository: neuvector/manager
    hash:
  priorityClassName:
  env:
    ssl: true
    envs: []
  svc:
    type: NodePort # should be set to - ClusterIP
    loadBalancerIP:
    annotations:
      {}
      # azure
      # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet"
  # OpenShift Route configuration
  # Make sure manager env ssl is false for edge termination
  route:
    enabled: true
  certificate:
    secret: ""
    keyFile: tls.key
    pemFile: tls.pem
  ingress:
    enabled: false
    host: neuvector.silverycat.de # MUST be set, if ingress is enabled
    ingressClassName: "traefik"
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: self-signed-cluster-issuer
      # kubernetes.io/ingress.class: my-nginx
      # nginx.ingress.kubernetes.io/whitelist-source-range: "1.1.1.1"
      # nginx.ingress.kubernetes.io/rewrite-target: /
      # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
      # only for end-to-end tls conf - ingress-nginx accepts backend self-signed cert
    tls: true
    secretName: neuvector-tls # my-tls-secret

  controller:
  enabled: true
  replicas: 3
  pvc:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: local-path
