apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.192.168.3.125.nip.io`)
      services:
        - name: argocd-server
          port: 443
  tls:
    certResolver: default
