apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.3.11-192.168.3.99
  - 192.168.3.201-192.168.3.241
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-first-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
