apiVersion: v1
kind: ResourceQuota
metadata:
  name: nextcloud-quota
  namespace: nextcloud
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1500m"
    limits.memory: "2Gi"
