apiVersion: v1
kind: Service
metadata:
  name: minio-service-internal
  namespace: minio-dev
spec:
  selector:
    app: minio
  externalIPs:
  - 192.168.1.66
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 31002
