apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-dev
spec:
  selector:
    app: minio
  externalIPs:
  - 192.168.1.66
  type: NodePort
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9090
      nodePort: 31001
