---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 999Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete #Retain
  storageClassName: local-path
  local:
    path: /mnt/backup-server/buckets1 #edit year the path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-server-pvc
  namespace: nextcloud
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 999Gi
  volumeName: nextcloud-pv
