apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #yourPvcName
  namespace: #yournamespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  resources:
    requests:
      storage: 999Gi
~                       
